/* for location actions */
export const FETCH_LOCATIONS = 'FETCH_LOCATIONS';
export const SET_LOCATIONS = 'SET_LOCATIONS';
export const SELECT_LOCATION = 'SELECT_LOCATION';
export const FETCH_LOCATION_ERROR = 'FETCH_LOCATION_ERROR';

export const SET_RESTAURANTS = 'SET_RESTAURANTS';
export const FETCH_RESTAURANTS_ERROR = 'FETCH_RESTAURANTS_ERROR';
